### ISSUE TITLE
proposition for instalation guide

### ISSUE THREAD

**Issue by PabsEdu** [NajmAjmal/sparxmaths#1]
this is not an issue with the code, but an issue with the installation guide.
I would recommend at the end of the instructions to state 'If sparx is open, refresh the page so the program can work, You can see that it is working when sparx is a different color'
aside from that, Great stuff since Sparx is not so bad aside from the Bookwork Checks so this is a great addon to have.

**Comment by NajmAjmal-old** [comment]
Hi @PabsEdu,

Thanks for your excellent extension. This is quite useful and may clear up confusion. I'll be sure to add it in the next version.

Thanks, Najm
