### ISSUE TITLE
UI Refresh has completely broken the app

### ISSUE THREAD

**Issue by realrandombeans** [NajmAjmal/sparxmaths#36]
A new UI refresh they've done has completely broken the color themes and the bookmark solver. This seems to be affecting everyone.

**Comment by NajmAjmal** [comment]
Hi @realrandombeans,

Thanks for bringing this to my attention. It seems this update to the sparx website has changed overall website structure. they now use random DIV names, which now makes it extremely difficult to use program features.

For an example;

Old: a class=".status-bar-label-text">XP/a>
New: a class="_XPCount_g7mut_68" href="/student/rewards">XP/a>

With the new change, we will now need to account for the additional class name. 

Thanks, Najm

**Comment by sulaymaanajmal** [comment]
```
let sparxSolver = dead;
console.log(dead)
```

**Comment by kincho4** [comment]
i havent looked at the sparx html properly yet but perhaps could use regex to find it????

**Comment by sulaymaanajmal** [comment]
I think @NajmAjmal has already looked into it and discovered that each html element class has a unique id for every user, for more information ask him, I'm not quite sure what he found out.

**Comment by kincho4** [comment]
> I think @NajmAjmal has already looked into it and discovered that each html element class has a unique id for every user, for more information ask him, I'm not quite sure what he found out. @kincho4 

Sure. I will try to help and research it to get this working again

**Comment by sulaymaanajmal** [comment]
> again

Great!

**Comment by kincho4** [comment]
> I think @NajmAjmal has already looked into it and discovered that each html element class has a unique id for every user, for more information ask him, I'm not quite sure what he found out. @kincho4

i just realised that we might jsut have to change the html names in here and it will be up and running. i have the same as him so i doubt it would be a user id thing. but as long as it does not keep changing even if it is unique we could make something where users put there own id.
![image](https://github.com/NajmAjmal/sparxmaths/assets/75807467/d757a62d-abcb-4445-9508-3c2f270fa96f)

**Comment by NajmAjmal** [comment]
Hi @kincho4, 

This piece of info is interesting, I assumed it maybe random for all users etc. but that does not seem to be the case. This specific area can easily be fixed. The problem lies with bookwork codes and answers. They have also updated the structure on the website as well. Now it's more likely we can bring back the extension.

Thanks, Najm

**Comment by kincho4** [comment]
let me make a fix for the div change issue. would it be also better to have the script hosted on github so it would be easier for others to make changes. i can modify like it to do that. so it can inject from github raw file.

**Comment by NajmAjmal** [comment]
> let me make a fix for the div change issue. would it be also better to have the script hosted on github so it would be easier for others to make changes. i can modify like it to do that. so it can inject from github raw file.

Yes, currently the script (console.js) is hosted on GitHub. It can be modified any time. Any changes will be made live to all users.

**Comment by kincho4** [comment]
i meant the inject is on jsdelivr

**Comment by NajmAjmal** [comment]
Hi @kincho4 & @sulaymaanajmal,

We are going to use [Rosie's Azalea](https://github.com/acquitelol/azalea) as a base for our update. Their version still functions.

Thanks, Najm

**Comment by acquitelol** [comment]
> Hi @kincho4 & @sulaymaanajmal,
> 
> We are going to use [Rosie's Azalea](https://github.com/acquitelol/azalea) as a base for our update. Their version still functions.
> 
> Thanks, Najm

It doesn't "still function". It functions because I spent hours rewriting most of the codebase to allow it to still function.
