### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by acquitelol** [NajmAjmal/sparxmaths#38]
Hi! I saw that you forked my [azalea](https://github.com/acquitelol/azalea) project, then moved over the files into this repository. However, I noticed that this did not have the original licence included in the repo from which you are implenting your code, aswell as the "forked from acquitelol/azalea" tag not being present either. On another note, I would like to request that you do not directly fork Azalea and rebrand it to Sintco, as I really would like it to stay as Azalea. You are free to reference code from it, but where it stands right now I'm not sure whether you will be able to actively maintain the codebase, as it is significantly more complex than the old extension that was previously here. Furthermore, if you do not include the original license provided in Azalea, DMCA legal action will concur.

Love, Rosie 💖

**Comment by NajmAjmal** [comment]
Hi @acquitelol,

I hope these changes are alright with you. If not, do let me know.
https://github.com/NajmAjmal/sparxmaths/tree/license-acquitelol



Thanks, Najm

**Comment by acquitelol** [comment]
Hi, thank you. 

That should be fine, however my intention was to request that the project was not built upon at all, as it a relatively complicated codebase and, basing my opinion on the previous code and the CDN repo of the Sintco organisation, you do not have the skills to actively maintain the codebase. As the license is MIT, legally I cannot stop you from using the code you have already implemented. However, morally I can still request it. Further commits to the Azalea codebase are licensed under copyright raw, and so all rights are reserved to me, meaning I can deny use to any changes past the commit copied into this repository. In simple terms , you will need to maintain the internal code yourself, of what is already committed to this repository, as you are not permitted to use code added in any further commits to Azalea or to sync the codebase here. Please do not take this as a personal attack or anything of the sort, as it is absolutely not, however I spent a very long time working on this project and would just like to protect my rights.

- Rosie 💝
