### ISSUE TITLE
COLLAB

### ISSUE THREAD

**Issue by Scriptifer** [NajmAjmal/sparxmaths#4]
I can self-host your website and buy the domain for it myself, you can send me the contents of the page and I will self-host it, and better domains like sparx-solver.uk or .com

**Comment by NajmAjmal** [comment]
Hi @Scriptifer,

Which website are you talking about?
This is an extension, not a website. Please clarify in more detail.

Thanks, Najm

**Comment by Scriptifer** [comment]
This
https://sparxmaths.glitch.me/

**Comment by NajmAjmal** [comment]
Hi @Scriptifer,

Suggest an external messaging platform where we can continue this conversation.

**Comment by Scriptifer** [comment]
Discord
Discord username: scriptifer
