### ISSUE TITLE
Copyright -

### ISSUE THREAD

**Issue by frosted13** [NajmAjmal/sparxmaths#43]

**Comment by frosted13** [comment]
why did you close it

**Comment by NajmAjmal** [comment]
Hi @frosted13,

**Comment by NajmAjmal** [comment]
Could you describe your issue in further detail

**Comment by frosted13** [comment]
I just did until you deleted it

**Comment by frosted13** [comment]
The bookwork highlighter isn't working

**Comment by NajmAjmal** [comment]
> they closed it because theyre trying to actively censor me from saying that they stole my code and are trying to claim it as theirs 💖

I do not claim it is mine

**Comment by frosted13** [comment]
> they closed it because theyre trying to actively censor me from saying that they stole my code and are trying to claim it as theirs 💖

so like you technically own this

**Comment by acquitelol** [comment]
> > they closed it because theyre trying to actively censor me from saying that they stole my code and are trying to claim it as theirs 💖
> 
> 
> 
> I do not claim it is mine

i meannnn asking for permission is nice, if you deleted the issue earlier of me saying you took the code you seem to be trying to hide something, and its not that the extension doesnt work

**Comment by maisymoe** [comment]
> > they closed it because theyre trying to actively censor me from saying that they stole my code and are trying to claim it as theirs 💖
> 
> so like you technically own this

rosie does own this - if you'd like a working version, visit https://github.com/acquitelol/azalea

**Comment by frosted13** [comment]
> > > they closed it because theyre trying to actively censor me from saying that they stole my code and are trying to claim it as theirs 💖
> > 
> > 
> > so like you technically own this
> 
> rosie does own this - if you'd like a working version, visit https://github.com/acquitelol/azalea

thanks

**Comment by acquitelol** [comment]
> > > so like you technically own this
> 
> > > @frosted13
> 
> > 
> 
> > rosie does own this - if you'd like a working version, visit https://github.com/acquitelol/azalea
> 
> 
> 
> @aquitelol has programmed code in this repo

i have programmed nothing in this repo, the code in this repo is code that you took from azalea lmao

**Comment by NajmAjmal** [comment]
@acquitelol code has been used in this repo, and they have been accredited for it

**Comment by acquitelol** [comment]
> 
> 
> 
> 
> > > > they closed it because theyre trying to actively censor me from saying that they stole my code and are trying to claim it as theirs 💖
> 
> > > 
> 
> > > 
> 
> > > so like you technically own this
> 
> > 
> 
> > rosie does own this - if you'd like a working version, visit https://github.com/acquitelol/azalea
> 
> 
> 
> thanks

note that bookwork logging is not working as of the v2 update in azalea because i still need to fix the patch for the question container, however themes and settings work, if you go to the top right and hover over any item

**Comment by frosted13** [comment]
> > > > > they closed it because theyre trying to actively censor me from saying that they stole my code and are trying to claim it as theirs 💖
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > so like you technically own this
> > 
> > 
> > > 
> > 
> > 
> > > rosie does own this - if you'd like a working version, visit https://github.com/acquitelol/azalea
> > 
> > 
> > thanks
> 
> note that bookwork logging is not working as of the v2 sparx update in azalea because i still need to fix the patch for the question container, however themes and settings work, if you go to the top right and hover over any item

Thanks for answering my question

**Comment by acquitelol** [comment]
> @acquitelol code has been used in this repo, and they have been accredited for it

yes, however when i politely asked that code was not used my issue was closed without even a reply, nor was i ever asked permission or even notified that my code was being used

even if the license allowed for it at the time, its still morally correct to ask permission or at least notify the person before you copy an entire repo and rebrand it to your own branding

**Comment by nexpid** [comment]
doesn't this basically count as a fork? yet Rosie is credited at the very bottom of the readme

**Comment by NajmAjmal** [comment]
https://github.com/acquitelol/azalea/blob/azalea-1694299581/LICENSE

> > @acquitelol code has been used in this repo, and they have been accredited for it
> 
> yes, however when i politely asked that code was not used my issue was closed without even a reply, nor was i ever asked permission or even notified that my code was being used
> 
> even if the license allowed for it at the time, its still morally correct to ask permission or at least notify the person before you copy an entire repo and rebrand it to your own branding

**Comment by acquitelol** [comment]
> https://github.com/acquitelol/azalea/blob/azalea-1694299581/LICENSE
> 
> 
> 
> > > @acquitelol code has been used in this repo, and they have been accredited for it
> 
> > 
> 
> > yes, however when i politely asked that code was not used my issue was closed without even a reply, nor was i ever asked permission or even notified that my code was being used
> 
> > 
> 
> > even if the license allowed for it at the time, its still morally correct to ask permission or at least notify the person before you copy an entire repo and rebrand it to your own branding
> 
> 
> 
> 

legality and morality are different

**Comment by NajmAjmal** [comment]
> doesn't this basically count as a fork? yet Rosie is credited at the very bottom of the readme

Yes, but not a direct fork via GitHub

**Comment by kincho4** [comment]
> they closed it because theyre trying to actively censor me from saying that they stole my code and are trying to claim it as theirs 💖

there is no need to act rude.

**Comment by acquitelol** [comment]
> > they closed it because theyre trying to actively censor me from saying that they stole my code and are trying to claim it as theirs 💖
> 
> 
> 
> there is no need to act rude. 

i was not! i was simply stating the facts :3

**Comment by NajmAjmal** [comment]
> > > they closed it because theyre trying to actively censor me from saying that they stole my code and are trying to claim it as theirs 💖
> > 
> > 
> > there is no need to act rude.
> 
> i was not! i was simply stating the facts :3

Why would anyone try to censor you? 

And I have not stolen your code. I've left you credit and as you have stated [here](https://github.com/acquitelol/azalea/releases/tag/azalea-1694389024), the code was under MIT licence, meaning anyone can use it.

**Comment by acquitelol** [comment]
yeah sure can we end this argument please 😭

**Comment by NajmAjmal** [comment]
> they closed it because theyre trying to actively censor me from saying that they stole my code and are trying to claim it as theirs 💖

So is this true?
