### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by ExoWizzz** [NajmAjmal/sparxmaths#5]
it changes the sparx colour but doesnt like highlight any answers
just to clarify does it only highlights book work or answers of every qustion cuz i am not looking to solve my bookwork but actuall answers
![Screenshot (6)](https://github.com/NajmAjmal/sparxmaths/assets/85681940/6a56b987-fea1-4177-9788-5a8a31a2b863)
i see nothing highlighted 
trying to my homewrokd for like an hour

**Comment by NajmAjmal** [comment]
Hi @HamzahHussain1102,

This extension eliminates Bookwork checks and adds custom Colour themes. It does not *solve* your Sparxmaths questions.

Thanks, Najm
