### ISSUE TITLE
No Bookwork Code Answers >:(

### ISSUE THREAD

**Issue by kdacygithub** [NajmAjmal/sparxmaths#58]
Ok so it works as the theme has changed, but it won't show me the answers to bookwork codes >:(

**Comment by Adam-1023** [comment]
I also have this problem the website turns pink but does not give any answers.

**Comment by kdacygithub** [comment]
> I also have this problem the website turns pink but does not give any answers.

Same

**Comment by StefCoders** [comment]
Website has a new version & look.

**Comment by kdacygithub** [comment]
> Website has a new version & look.

I know? How does that factor into my issue?

**Comment by NajmAjmal** [comment]
Hi @kdacygithub,

I recommend using [Azalea](https://github.com/acquitelol/azalea). It is better than this extension.
